# Generated by Django 4.1 on 2022-08-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="covidcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(max_length=200, null=True)),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("Alappuzha", "Alappuzha"),
                            ("Wayanad", "Wayanad"),
                            ("Ernakulam", "Ernakulam"),
                            ("Thrissur", "Thrissur"),
                            ("Thiruvananthapuram", "Thiruvananthapuram"),
                            ("Pathanamthitta", "Pathanamthitta"),
                            ("Palakkad", "Palakkad"),
                            ("Malappuram", "Malappuram"),
                            ("Kozhikode", "Kozhikode"),
                            ("Kottayam", "Kottayam"),
                            ("Kollam", "Kollam"),
                            ("Kasaragod", "Kasaragod"),
                            ("Kannur", "Kannur"),
                            ("Idukki", "Idukki"),
                        ],
                        max_length=50,
                    ),
                ),
                ("covidcases", models.CharField(max_length=40, null=True)),
                ("numberofvaccination", models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="covidoutbreaks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(max_length=200, null=True)),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("Alappuzha", "Alappuzha"),
                            ("Wayanad", "Wayanad"),
                            ("Ernakulam", "Ernakulam"),
                            ("Thrissur", "Thrissur"),
                            ("Thiruvananthapuram", "Thiruvananthapuram"),
                            ("Pathanamthitta", "Pathanamthitta"),
                            ("Palakkad", "Palakkad"),
                            ("Malappuram", "Malappuram"),
                            ("Kozhikode", "Kozhikode"),
                            ("Kottayam", "Kottayam"),
                            ("Kollam", "Kollam"),
                            ("Kasaragod", "Kasaragod"),
                            ("Kannur", "Kannur"),
                            ("Idukki", "Idukki"),
                        ],
                        max_length=50,
                    ),
                ),
                ("covidcases", models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="futurecovid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(max_length=200, null=True)),
                (
                    "district",
                    models.CharField(
                        choices=[
                            ("Alappuzha", "Alappuzha"),
                            ("Wayanad", "Wayanad"),
                            ("Ernakulam", "Ernakulam"),
                            ("Thrissur", "Thrissur"),
                            ("Thiruvananthapuram", "Thiruvananthapuram"),
                            ("Pathanamthitta", "Pathanamthitta"),
                            ("Palakkad", "Palakkad"),
                            ("Malappuram", "Malappuram"),
                            ("Kozhikode", "Kozhikode"),
                            ("Kottayam", "Kottayam"),
                            ("Kollam", "Kollam"),
                            ("Kasaragod", "Kasaragod"),
                            ("Kannur", "Kannur"),
                            ("Idukki", "Idukki"),
                        ],
                        max_length=50,
                    ),
                ),
                ("covidcases", models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
