# Generated by Django 4.1 on 2022-08-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="mark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(max_length=200, null=True)),
                (
                    "subjects",
                    models.CharField(
                        choices=[
                            ("malayalam", "malayalam"),
                            ("english", "english"),
                            ("hindi", "hindi"),
                            ("maths", "maths"),
                        ],
                        max_length=50,
                    ),
                ),
                ("result", models.CharField(max_length=40, null=True)),
                ("pass_mark", models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.DeleteModel(name="covidcase",),
        migrations.DeleteModel(name="covidoutbreaks",),
        migrations.DeleteModel(name="futurecovid",),
    ]
