# Generated by Django 4.1 on 2022-08-09 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_mark_register"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mark", old_name="pass_mark", new_name="Grade",
        ),
    ]
